# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180626_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
